# Generated by Django 4.0.2 on 2022-02-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_news_category_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='published_date',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
