# Generated by Django 4.0.2 on 2022-02-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='author',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='category',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='category',
            name='text',
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
